# certificate-wildcard-domain.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-wildcard-domain
spec:
  secretName: cert-secret-wildcard-domain
  privateKey:
    rotationPolicy: Always
  commonName: '*.${DOMAIN_NAME}'
  dnsNames:
    - '*.${DOMAIN_NAME}'
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
